"""CharacterPose — ComfyUI custom nodes for identity-preserving pose transfer."""

from .nodes.pose import NODE_CLASS_MAPPINGS as POSE_MAPPINGS
from .nodes.pose import NODE_DISPLAY_NAME_MAPPINGS as POSE_DISPLAY
from .nodes.character import NODE_CLASS_MAPPINGS as CHAR_MAPPINGS
from .nodes.character import NODE_DISPLAY_NAME_MAPPINGS as CHAR_DISPLAY
from .nodes.caption import NODE_CLASS_MAPPINGS as CAPTION_MAPPINGS
from .nodes.caption import NODE_DISPLAY_NAME_MAPPINGS as CAPTION_DISPLAY
from .nodes.composer import NODE_CLASS_MAPPINGS as COMPOSER_MAPPINGS
from .nodes.composer import NODE_DISPLAY_NAME_MAPPINGS as COMPOSER_DISPLAY
from .nodes.render import NODE_CLASS_MAPPINGS as RENDER_MAPPINGS
from .nodes.render import NODE_DISPLAY_NAME_MAPPINGS as RENDER_DISPLAY
from .nodes.sheet import NODE_CLASS_MAPPINGS as SHEET_MAPPINGS
from .nodes.sheet import NODE_DISPLAY_NAME_MAPPINGS as SHEET_DISPLAY
from .nodes.warp import NODE_CLASS_MAPPINGS as WARP_MAPPINGS
from .nodes.warp import NODE_DISPLAY_NAME_MAPPINGS as WARP_DISPLAY

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(POSE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CHAR_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CAPTION_MAPPINGS)
NODE_CLASS_MAPPINGS.update(COMPOSER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RENDER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SHEET_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WARP_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(POSE_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CHAR_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(CAPTION_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(COMPOSER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(RENDER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(SHEET_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(WARP_DISPLAY)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
